#!/usr/bin/env bash
# Derive a TEST-ONLY bundle whose database migration is written to fail, for the
# rollback and restore drill.
#
# Why this script exists. The drill needs a release that gets as far as touching
# the schema and then breaks, so that an image rollback can be shown to be
# insufficient and the dump-backed restore necessary. No such release can come
# out of CI: `main` is branch-protected on four required jobs, so a migration
# written to fail could never be published, and `package-offline.sh` refuses any
# tree that is not exactly the commit named in its `images.lock`. The artifact
# therefore has to be made here, by hand, from a bundle that *was* CI-proven.
#
# What that costs, stated plainly:
#
#   * Resealing SHA256SUMS destroys the folder's self-attestation. The digest
#     this script prints attests to a locally mutated folder. It is NOT a
#     release digest and must never be recorded as one.
#   * The CI anchors that survive are the image ones. images.tar,
#     images.bundle.lock, ci-images.lock and IMAGES.lock are copied untouched,
#     so every container image in this artifact is still the digest-pinned set
#     that CI published for the source commit. Only the tree is altered.
#   * The alteration is exactly two files plus a marker, listed in
#     FAULT-INJECTION.json, and `--diff` will print it.
#
# The marker is not a courtesy. It is sealed into SHA256SUMS, so it cannot be
# removed without breaking verification, and verify-bundle.sh and
# install-offline.sh both refuse to stay quiet about it.
#
#   bash scripts/make-fault-injection-bundle.sh <verified-bundle> <destination>
#   bash scripts/make-fault-injection-bundle.sh --diff <fault-injection-bundle>
set -euo pipefail

MARKER="FAULT-INJECTION.json"
MIGRATION="db/migrations/900_fault_injection.sql"

die() { echo "$*" >&2; exit 1; }

# ------------------------------------------------------------------ --diff --
if [ "${1:-}" = "--diff" ]; then
  target="${2:?usage: bash scripts/make-fault-injection-bundle.sh --diff <bundle>}"
  cd "$target"
  test -f "$MARKER" || die "$target has no $MARKER: it is not a fault-injection artifact"
  echo "--- $MARKER"
  cat "$MARKER"
  echo "--- $MIGRATION"
  cat "$MIGRATION"
  echo "--- the migrate command in compose.yml"
  grep -n 'db/migrations/' compose.yml
  exit 0
fi

source_dir="${1:?usage: bash scripts/make-fault-injection-bundle.sh <verified-bundle> <destination>}"
dest_dir="${2:?usage: bash scripts/make-fault-injection-bundle.sh <verified-bundle> <destination>}"
repo="$(cd "$(dirname "$0")/.." && pwd)"

test -d "$source_dir" || die "no such bundle: $source_dir"
test ! -e "$dest_dir" || die "$dest_dir already exists; remove it or choose another path"
test ! -f "$source_dir/$MARKER" || die "$source_dir is already a fault-injection artifact; derive from a real release"

# The point of the drill is that a *good* release was mutated. Deriving one
# from a folder that never verified would prove nothing about either.
echo "== verifying the source bundle before mutating it =="
bash "$repo/scripts/verify-bundle.sh" "$source_dir"

source_version="$(cat "$source_dir/release-version.txt")"
source_sums="$(sha256sum "$source_dir/SHA256SUMS" | awk '{print $1}')"

echo "== copying =="
mkdir -p "$dest_dir"
# tar rather than cp -r: it preserves modes, and mode bits are one of the
# properties the transfer analysis measured.
(cd "$source_dir" && tar -cf - .) | (cd "$dest_dir" && tar -xf -)

cd "$dest_dir"

# ------------------------------------------------------------- the mutation --
# mkdir first: a bundle is not required to already carry db/migrations, and a
# redirect into a missing directory reports the file name rather than the
# directory, which sends whoever reads the error to the wrong place.
mkdir -p "$(dirname "$MIGRATION")"
cat > "$MIGRATION" <<'SQL'
-- DELIBERATELY FAILING MIGRATION -- TEST ARTIFACT ONLY.
--
-- Generated by scripts/make-fault-injection-bundle.sh for the upgrade/rollback
-- drill. This file exists only inside a fault-injection bundle; it is not in
-- the repository and no CI-published release contains it.
--
-- The first statement succeeds, so the migration is not a no-op: it takes a
-- real lock and writes a real row, which is what makes the point that rolling
-- the images back cannot undo it. The second statement then fails, and with
-- psql's ON_ERROR_STOP=1 the migrate service exits non-zero and the upgrade
-- stops with the schema already altered.
CREATE TABLE IF NOT EXISTS fault_injection_marker (
    id          integer PRIMARY KEY,
    applied_at  timestamptz NOT NULL DEFAULT now()
);
INSERT INTO fault_injection_marker (id) VALUES (1)
    ON CONFLICT (id) DO NOTHING;

-- The failure. A column that does not exist, named so that the drill's
-- transcript says why it stopped.
ALTER TABLE fault_injection_marker
    DROP COLUMN this_column_does_not_exist_and_the_migration_must_fail_here;
SQL

# compose.yml lists every migration explicitly -- there is no directory glob --
# so the new file has to be added to the psql invocation or it would never run.
# awk rather than python: the staging host is only promised bash and GNU
# coreutils, and a minimal Ubuntu server has no python3 either. Two passes --
# the first finds the last migration argument, the second copies the file and
# inserts after that line, matching its indentation.
last_migration="$(grep -n -- '-f /db/migrations/' compose.yml | tail -1 | cut -d: -f1)"
test -n "$last_migration" || die "compose.yml has no -f /db/migrations/ arguments to extend"
awk -v at="$last_migration" -v add="$MIGRATION" '
  { print }
  NR == at {
    match($0, /^[ \t]*/)
    printf "%s-f /%s\n", substr($0, 1, RLENGTH), add
  }
' compose.yml > compose.yml.tmp
mv compose.yml.tmp compose.yml
grep -q -- "-f /$MIGRATION" compose.yml || die "failed to add the migration to compose.yml"
echo "compose.yml: added -f /$MIGRATION after line $last_migration"

# ------------------------------------------------------------- the provenance --
cat > "$MARKER" <<JSON
{
  "artifact_kind": "fault-injection-test-bundle",
  "not_a_release": true,
  "warning": "This folder is a deliberately broken TEST artifact. It is not a CI-published release and must never be described as one. Its SHA256SUMS digest attests to a locally mutated folder.",
  "derived_from": {
    "release_version": "$source_version",
    "source_sha256sums": "sha256:$source_sums",
    "note": "That digest is the CI-anchored one. This folder no longer matches it."
  },
  "mutations": [
    "added $MIGRATION, whose second statement fails under ON_ERROR_STOP=1",
    "added one -f /$MIGRATION argument to the migrate command in compose.yml",
    "added this marker file",
    "resealed SHA256SUMS over the result"
  ],
  "unchanged": [
    "images.tar",
    "images.bundle.lock",
    "ci-images.lock",
    "IMAGES.lock",
    "models.lock",
    "release-version.txt"
  ],
  "images_are_still_ci_published": true,
  "created_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "created_by": "scripts/make-fault-injection-bundle.sh"
}
JSON

# --------------------------------------------------------------- the reseal --
# Byte-for-byte the same command package-offline.sh seals a real release with,
# so the folder stays installable -- and the same command is what makes this
# digest meaningless as provenance.
find . -type f ! -name SHA256SUMS ! -name .env -print0 \
  | sort -z | xargs -0 sha256sum > SHA256SUMS

echo "== verifying the mutated bundle =="
bash "$repo/scripts/verify-bundle.sh" .

new_sums="$(sha256sum SHA256SUMS | awk '{print $1}')"
cat <<EOF

Fault-injection artifact ready: $(pwd)
  derived from release : $source_version
  source SHA256SUMS    : sha256:$source_sums   (CI-anchored)
  this   SHA256SUMS    : sha256:$new_sums   (LOCAL MUTATION -- not a release digest)

Do not record the second digest as a release digest, and do not install this
artifact on any host you expect to keep. Its migration is written to fail after
it has already altered the schema, which is the whole point of the drill.
EOF
